spring:
  application:
    name: mini_library
  datasource:
    username: qirsam
    password: amidamaru
    url: jdbc:postgresql://localhost:5432/library_db
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        hbm2ddl.auto: validate
    open-in-view: false
  mvc:
    format:
      date: iso
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 698821590000-eq767db10mpad01pihei56lkrq4evnp7.apps.googleusercontent.com
            clientSecret: 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
            redirectUri: http://www.qirsam.com/login/oauth2/code/google
  messages:
    basename: messages
server:
  port: 8080

app.image.bucket : /home/qirsam/IdeaProjects/mini_library/images
